name: build+run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-riscv64-linux-gnu qemu-system-misc

    - name: build
      run: make

    - name: boot test
      run: |
        timeout 10s make run || code=$?
        if [ "$code" -eq 124 ]; then echo "PASS (halted on time)"; exit 0; fi
        exit $code
